server:
  port: 8781
spring:
  application:
    name: api-driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: api-driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: redis