server:
  port: 8481
spring:
  application:
    name: service-map
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: service-map

# 自定义属性
aMap:
  key: 161fa2b7db6f2a5190e16f4af097aca5