server:
  port: 8081
spring:
  application:
    name: api-Passenger
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: api-Passenger
  redis:
    host: 192.168.19.149
    port: 6379
    database: 0
    password: redis