server:
  port: 8881
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: gyh155222334
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: service-order
  redis:
    host: 192.168.19.151
    port: 6379
    database: 0
    password: redis